### PR TITLE
Adding "pipe" ability to ios_system

### PR DESCRIPTION
**Pull request by holzschu**
I would like to add one pull request. This one adds the ability to pipe commands, i.e. `ls -lR | grep \.cpp` or `ls -lR | sed -n 2,23p`. We can even multi-pipe (`ls | grep | sed | sed`). 

As an added bonus:
- the "ssh" command. It lets you connect to another machine and execute a command remotely: `ssh user@host "ls -lhrt ~"` (but not run an interactive shell)
- the "tee" command, because some scripts use it
- a more explicit error message for scp/sftp
- getopt_long.c included, meaning gzip and grep are more stable.

### CODE REVIEW

**Comment by louisdh** [comment]
Awesome, thanks!

**Comment by louisdh** [comment]
@holzschu Since this PR the project doesn't seem to compile for the simulator anymore:
```
Undefined symbols for architecture x86_64:
  "_res_9_init", referenced from:
      _w_main in w.o
ld: symbol(s) not found for architecture x86_64
```

I believe this is related to the `w` command (in shell_cmds).
Would you mind taking a look?

**Comment by holzschu** [comment]
> On 24 Jan 2018, at 22:26, louisdh <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> @holzschu <https://github.com/holzschu> Since this PR the project doesn't seem to compile for the simulator anymore:
> 
> Undefined symbols for architecture x86_64:
>   "_res_9_init", referenced from:
>       _w_main in w.o
> ld: symbol(s) not found for architecture x86_64
> I believe this is related to the w command (in shell_cmds).
> Would you mind taking a look?
> 

I've met this one before. It's related to libresolv.9.tbd which needs to be added to the list of "linked frameworks and libraries". 

It probably got removed during the xcodeproj merging. 
 
Nicolas

**Comment by holzschu** [comment]
> On 24 Jan 2018, at 23:49, n.holzschuch@free.fr <mailto:n.holzschuch@free.fr> wrote:
> 
> 
> 
>> On 24 Jan 2018, at 22:26, louisdh <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> @holzschu <https://github.com/holzschu> Since this PR the project doesn't seem to compile for the simulator anymore:
>> 
>> Undefined symbols for architecture x86_64:
>>   "_res_9_init", referenced from:
>>       _w_main in w.o
>> ld: symbol(s) not found for architecture x86_64
>> I believe this is related to the w command (in shell_cmds).
>> Would you mind taking a look?
>> 
> 
> I've met this one before. It's related to libresolv.9.tbd which needs to be added to the list of "linked frameworks and libraries". 
> 
> It probably got removed during the xcodeproj merging. 

It should work with the latest commit/push (this morning).

Let me know if it doesn't work.

Nicolas

**Pull request merged**
