### PR TITLE
Changed project & submodules so it uses frameworks instead of dylibs

### PR DESCRIPTION
**Pull request by holzschu**
As requested by Apple and issues #103, this PR changes project.pbxproj, the ios_system submodule and the network_ios submodule so they use dynamic frameworks instead of dynamic libraries. 

Let's hope this is sufficient for AppStore rules.

### CODE REVIEW

**Comment by dennis90joling** [comment]
Im need help openterm is new for my

**Comment by holzschu** [comment]
Progress: this branch is now failing in the testing stage.

**Comment by louisdh** [comment]
This compiles on Travis CI, but when I compile locally I get the following error in `network_ios`, `shell` and `files`:
```
'ios_error.h' file not found
```

🤔

**Comment by holzschu** [comment]
Hi, 
> On 29 Mar 2018, at 18:35, louisdh <notifications@github.com> wrote:
> 
> This compiles on Travis CI, but when I compile locally I get the following error in network_ios, shell and files:
> 
> 'ios_error.h' file not found

Is that before or after running the "get_frameworks.sh" script?

**Comment by louisdh** [comment]
Nvm, running `./bootstrap.sh` fixes it.

**Pull request merged**
