### PR TITLE
Switched ios_system to be a submodule

### PR DESCRIPTION
**Pull request by IMcD23**
Unless I'm mistaken, there is no need for us to have a copy of the `ios_system` sources in OpenTerm. Instead, we should use a submodule, for the reasons described here: #93.

This change removes all of `ios_system` in the `Dependencies` folder, and replaces them with a submodule.

It adds a `bootstrap.sh` script to run which sets up `ios_system`. I also updated the README & travis.yml to reflect these changes.

### CODE REVIEW

**Comment by louisdh** [comment]
One thing I really like about the current approach to dependencies in OpenTerm is that everything is contained in the repo. You can check out any commit and the project will build, this even works if you're offline. That's also the reason the pods folder is included in this repo. 

That doesn't mean that the current approach to how ios_system is included is perfect, but I'm not sure if it's worth it removing the sources from this repo.

**Comment by IMcD23** [comment]
When using a submodule, ios_system will be pinned to a specific commit. We will still be guaranteed a stable build of OpenTerm, even if we want to go back in time.

With a submodule, updating to a newer version of ios_system just means changing that stored commit.

Additionally, if there are changes in ios_system that we want to try out before committing to master, we can easily do that since the `Dependencies/ios_system` directory is effectively its own repository. That means you can `git pull` or `git checkout` inside there, and it pulls from `https://github.com/holzschu/ios_system.git`

**Comment by louisdh** [comment]
Sorry for the long wait!

**Comment by louisdh** [comment]
One problem that was caused by this PR is that unavailable commands now show up. E.g. "lua", trying to use it results in "Failed loading lua from lua_ios.framework"

**Comment by IMcD23** [comment]
Interesting. I know that @holzschu recently switched to using a property list to store the available commands. Will it be possible to use our own version instead?

**Comment by louisdh** [comment]
It appears that's caused by `#define SIDELOADING` in `ios_system.m`.

**Comment by louisdh** [comment]
The property list usage hasn't been merged in ios_system's master branch yet.

**Comment by holzschu** [comment]
Yes indeed, if you want to hide the mechanisms, you need to comment the `#define SIDELOADING` line. It's unrelated to the switch to property list.

The basic idea is that, if you're sideloading, you don't mind knowing about the application structure and having debug messages. I can change that if it helps. What would you suggest? Global variable?

**Comment by louisdh** [comment]
It might make more sense if `SIDELOADING` was **not** defined by default in ios_system.

**Comment by holzschu** [comment]
Done.

**Comment by louisdh** [comment]
Thanks!

**Pull request merged**
